import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif, Zalando_Sans_Expanded } from "next/font/google";
import "./globals.css";

const zalandoSansExpanded = Zalando_Sans_Expanded({
  variable: "--font-zalando-sans",
  subsets: ["latin"],
  weight: ["400"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${zalandoSansExpanded.variable} ${instrumentSerif.variable} h-full antialiased font-zalando-sans`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
